"""prova database2

Revision ID: 967c7f00e5da
Revises: eb6e246374d3
Create Date: 2020-03-05 11:43:35.942238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967c7f00e5da'
down_revision = 'eb6e246374d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('idJob', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=45), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('uniprotid', sa.String(length=6), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('idJob')
    )
    op.create_table('model',
    sa.Column('idModel', sa.Integer(), nullable=False),
    sa.Column('pdbFile', sa.String(length=200), nullable=True),
    sa.Column('idJob', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idJob'], ['job.idJob'], ),
    sa.PrimaryKeyConstraint('idModel'),
    sa.UniqueConstraint('idJob'),
    sa.UniqueConstraint('pdbFile')
    )
    op.create_table('energy',
    sa.Column('idEnergy', sa.Integer(), nullable=False),
    sa.Column('zrank', sa.String(length=45), nullable=False),
    sa.Column('fold_energy', sa.String(length=45), nullable=False),
    sa.Column('rosetta_energy', sa.String(length=45), nullable=False),
    sa.Column('idModel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idModel'], ['model.idModel'], ),
    sa.PrimaryKeyConstraint('idEnergy'),
    sa.UniqueConstraint('idModel')
    )
    op.alter_column('user', 'adress',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('user', 'institution',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('user', 'institution',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('user', 'adress',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.drop_table('energy')
    op.drop_table('model')
    op.drop_table('job')
    # ### end Alembic commands ###
