"""test

Revision ID: ea09c5915bfb
Revises: 
Create Date: 2020-03-05 13:12:14.652430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea09c5915bfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('adress', sa.String(length=45), nullable=False),
    sa.Column('password_hash', sa.String(length=45), nullable=False),
    sa.Column('institution', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_adress'), 'user', ['adress'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('job',
    sa.Column('idJob', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=45), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('uniprotid', sa.String(length=6), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('idJob')
    )
    op.create_table('model',
    sa.Column('idModel', sa.Integer(), nullable=False),
    sa.Column('pdbFile', sa.String(length=200), nullable=True),
    sa.Column('idJob', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idJob'], ['job.idJob'], ),
    sa.PrimaryKeyConstraint('idModel'),
    sa.UniqueConstraint('idJob'),
    sa.UniqueConstraint('pdbFile')
    )
    op.create_table('energy',
    sa.Column('idEnergy', sa.Integer(), nullable=False),
    sa.Column('zrank', sa.String(length=45), nullable=False),
    sa.Column('fold_energy', sa.String(length=45), nullable=False),
    sa.Column('rosetta_energy', sa.String(length=45), nullable=False),
    sa.Column('idModel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idModel'], ['model.idModel'], ),
    sa.PrimaryKeyConstraint('idEnergy'),
    sa.UniqueConstraint('idModel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy')
    op.drop_table('model')
    op.drop_table('job')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_adress'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
